services:
  soh.process.server:
    image: soh.process.server
    build:
      context: .
      dockerfile: SOH.Process.Server/Dockerfile
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379/tcp"
    working_dir: /data
