//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOH.Process.Server.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SOH.Process.Server.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ferry_transfer_model_description {
            get {
                return ResourceManager.GetString("ferry_transfer_model_description", resourceCulture);
            }
        }
        
        public static string ferry_transfer_model_title {
            get {
                return ResourceManager.GetString("ferry_transfer_model_title", resourceCulture);
            }
        }
        
        public static string ferry_transfer_output_agents {
            get {
                return ResourceManager.GetString("ferry_transfer_output_agents", resourceCulture);
            }
        }
        
        public static string ferry_transfer_output_agents_title {
            get {
                return ResourceManager.GetString("ferry_transfer_output_agents_title", resourceCulture);
            }
        }
        
        public static string model_self_description {
            get {
                return ResourceManager.GetString("model_self_description", resourceCulture);
            }
        }
        
        public static string simulation_progress__0_ {
            get {
                return ResourceManager.GetString("simulation_progress {0}", resourceCulture);
            }
        }
        
        public static string simulation_finised__0_ {
            get {
                return ResourceManager.GetString("simulation_finised {0}", resourceCulture);
            }
        }
        
        public static string process_finished {
            get {
                return ResourceManager.GetString("process_finished", resourceCulture);
            }
        }
        
        public static string green_4_bikes_model_description {
            get {
                return ResourceManager.GetString("green_4_bikes_model_description", resourceCulture);
            }
        }
        
        public static string green_4_bikes_model_title {
            get {
                return ResourceManager.GetString("green_4_bikes_model_title", resourceCulture);
            }
        }
        
        public static string green_4_bikes_output_agents {
            get {
                return ResourceManager.GetString("green_4_bikes_output_agents", resourceCulture);
            }
        }
        
        public static string soh_output_statistics_avg_travel_time {
            get {
                return ResourceManager.GetString("soh_output_statistics_avg_travel_time", resourceCulture);
            }
        }
        
        public static string soh_output_agents {
            get {
                return ResourceManager.GetString("soh_output_agents", resourceCulture);
            }
        }
        
        public static string soh_output_avg_road_count_desc {
            get {
                return ResourceManager.GetString("soh_output_avg_road_count_desc", resourceCulture);
            }
        }
        
        public static string soh_output_avg_road_count {
            get {
                return ResourceManager.GetString("soh_output_avg_road_count", resourceCulture);
            }
        }
    }
}
